server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/mcp_app
spring.datasource.username=username
spring.datasource.password=password
app.jwt.secret=secret
app.jwt.access-token-minutes=15
app.jwt.refresh-token-days=14
# ===== app.storage.path=storage =====
spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate

# ===== STORAGE PATH =====
app.storage.path=./storage

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ===== ERROR DETAIL (DEV) =====
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-exception=true
server.error.include-stacktrace=always

# ===== JPA DEBUG =====
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

